Celtofar
islamkazproject/converterfartocel pull request #2
Opened 2022-08-23 17:46 UTC by islamkazproject

Написать функцию конвертации Цельсии в Фаренгейт! - OK!
Добавить тесты! -> OK!

2022-08-24 14:43 UTC, wbwswt requested changes

2022-08-24 14:43 UTC, wbwswt commented on .vscode/settings.json
> +{
Это не должно попадать в репу

2022-08-24 14:43 UTC, wbwswt commented on .vscode/.gitignore
> +.vscode/
__pycache__ забыл

2022-08-24 14:43 UTC, wbwswt commented on converterfartocel.py
> +def cel_to_far(cels):
Нет доки на модуль

2022-08-24 14:43 UTC, wbwswt commented on converterfartocel.py
> +def cel_to_far(cels):
Нет типов

2022-08-24 14:43 UTC, wbwswt commented on converterfartocel.py
> +def cel_to_far(cels):
Нет докстринга на функцию

2022-08-24 14:43 UTC, wbwswt commented on converterfartocel.py
> +    return (cels * 9 / 5) + 32
Если на вход подадут -274 вернется неправильный ответ

2022-08-24 14:43 UTC, wbwswt commented on converterfartocel.py
> +# if __name__ == "__main__":
Комменты в мастер не должны попадать

2022-08-24 14:43 UTC, wbwswt commented on pyproject.toml
> +flake8 = "^5.0.3"
Это дев-зависимости, им тут не место

2022-08-25 15:23 UTC, wbwswt commented on .vscode/settings.json
> +    "python.linting.pylintEnabled": false,
Удали файл из гита

2022-08-27 15:01 UTC, islamkazproject commented on .vscode/settings.json
> +{
![image](https://user-images.githubusercontent.com/39201439/187035829-175d623e-ac70-4098-8bd1-353f1af6efbd.png)

2022-08-27 15:01 UTC, islamkazproject commented on .vscode/.gitignore
> +.vscode/
![image](https://user-images.githubusercontent.com/39201439/187035836-aa2354b8-9af2-4ed8-9491-df0b5fe3fcfb.png)

2022-08-27 15:02 UTC, islamkazproject commented on .vscode/.gitignore
> +.vscode/
![image](https://user-images.githubusercontent.com/39201439/187035849-ad51f3e7-3930-4b82-8f40-703060ac5d88.png)

2022-08-27 15:02 UTC, islamkazproject commented on converterfartocel.py
> +def cel_to_far(cels):
![image](https://user-images.githubusercontent.com/39201439/187035863-fac2b596-6485-4dc6-bf6e-f8a9701ea2fd.png)

2022-08-27 15:03 UTC, islamkazproject commented on converterfartocel.py
> +    return (cels * 9 / 5) + 32
![image](https://user-images.githubusercontent.com/39201439/187035886-cf15b88a-359a-4440-8905-9d4991b519c7.png)
![image](https://user-images.githubusercontent.com/39201439/187035907-1e20e003-dd1d-464a-97f8-7e3b23d30303.png)
![image](https://user-images.githubusercontent.com/39201439/187035896-47f6c915-235f-4ee0-b92e-16c74461625c.png)

2022-08-27 15:04 UTC, islamkazproject commented on converterfartocel.py
> +# if __name__ == "__main__":
Убрал

2022-08-27 15:04 UTC, islamkazproject commented on pyproject.toml
> +flake8 = "^5.0.3"
![image](https://user-images.githubusercontent.com/39201439/187035940-e3085817-6f5e-4fa7-9f83-6dbdc4e85aab.png)

2022-08-27 15:06 UTC, islamkazproject commented on .vscode/settings.json
> +    "python.linting.pylintEnabled": false,
![image](https://user-images.githubusercontent.com/39201439/187035970-15765789-bc90-449e-a86f-4d87c5b5acb3.png)

2022-08-27 15:06 UTC, islamkazproject commented on converterfartocel.py
> +def cel_to_far(cels):
Не знаю что писать 
в док

2022-09-02 13:36 UTC, closed without merging